import './globals.css'
import {LoginProvider} from './context/context'
import { Montserrat } from 'next/font/google'
const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'ITSA-G2T1',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <LoginProvider>
      <body className={montserrat.className + " bg-[#050a24]"}>
        {children}
      </body>
      </LoginProvider>
    </html>
  )
}
