# Name of this GitHub Actions workflow.
name: Semgrep Differential

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request:
    types: [opened, synchronize, reopened]
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["master", "main"]

jobs:
  semgrep-full:
    name: Semgrep Full Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      # step 1
      - name: clone application source code
        uses: actions/checkout@v3

      # step 2
      - name: full scan
        run: |
          semgrep \
            --sarif --output report.sarif \
            --metrics=off \
            --config="p/default"

      # step 3
      - name: save report as pipeline artifact
        uses: actions/upload-artifact@v3
        with:
          name: report.sarif
          path: report.sarif

      # step 4
      - name: publish code scanning alerts
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: report.sarif
          category: semgrep
